# GA1-220501094-01-AA1-EV04 – Fundamentos en Pandas
## Explorando Instacart: descubre patrones de compra con Python y Pandas

**Aprendiz:** Juan Diego Mejía Llano
**Rol:** analista de datos de Instacart

# Momento 1. Comprensión del problema y reconocimiento de los datos

## Descripción del problema

Instacart dispone de información sobre los pedidos realizados por sus clientes, los productos comprados, los horarios de compra y la frecuencia con la que los usuarios vuelven a comprar. El equipo de análisis necesita saber qué información contienen los archivos y cómo consultarla para responder preguntas sobre el comportamiento de los clientes.

El objetivo de esta actividad es explorar los datos mediante Python y Pandas para conocer su estructura, consultar registros específicos y obtener indicadores básicos que permitan comprender los hábitos de compra.

**Pregunta orientadora:** ¿Cómo utilizar Python y la librería Pandas para explorar los datos de Instacart, identificar las características de los pedidos y productos, y obtener información relevante sobre los hábitos de compra de sus clientes?

## Archivos suministrados y qué información almacena cada uno

| N.º | Archivo | Qué almacena | Una fila representa |
|---|---|---|---|
| 1 | `instacart_orders.csv` | Los pedidos: quién los hizo, qué número de pedido es para ese cliente, el día de la semana, la hora y los días transcurridos desde su pedido anterior. | Un pedido |
| 2 | `products.csv` | El catálogo de productos con su nombre y su clasificación por pasillo y departamento. | Un producto |
| 3 | `aisles.csv` | Los nombres de los pasillos usados para clasificar los productos. | Un pasillo |
| 4 | `departments.csv` | Los nombres de los departamentos o categorías generales. | Un departamento |
| 5 | `order_products.csv` | Los artículos incluidos en cada pedido, su posición al agregarse al carrito y si son una recompra. | Un artículo dentro de un pedido |

## Columnas que identifican pedidos, usuarios y productos

| Concepto | Columna | Dónde aparece |
|---|---|---|
| Pedido | `order_id` | `instacart_orders.csv` y `order_products.csv` |
| Usuario (cliente) | `user_id` | `instacart_orders.csv` |
| Producto | `product_id` | `products.csv` y `order_products.csv` |
| Pasillo | `aisle_id` | `products.csv` y `aisles.csv` |
| Departamento | `department_id` | `products.csv` y `departments.csv` |

## Preguntas de análisis

1. ¿A qué horas del día se registran los pedidos y cuál es la distribución de los pedidos por hora?
2. ¿Qué productos pertenecen al departamento 1 y cuántos registros cumplen esta condición?
3. ¿Qué proporción de los registros de artículos corresponde a productos que ya habían sido comprados anteriormente?

## Importancia de explorar los datos antes de analizarlos

Explorar los datos antes de analizarlos permite conocer su estructura, identificar las columnas disponibles, reconocer valores ausentes o duplicados y detectar limitaciones que pueden afectar los resultados. Si se calcula un indicador sin esta revisión, se puede confundir, por ejemplo, el número de filas con el número de clientes, o sacar promedios sobre columnas incompletas sin saberlo. La exploración también facilita elegir los registros adecuados y realizar los cálculos correctamente.

# Momento 2. Importación y exploración inicial de los archivos

Se importa Pandas con el alias `pd` y se cargan los cinco archivos. Todos usan punto y coma (`;`) como separador, por eso se indica `sep=";"`. Los archivos están en la carpeta `data/` del proyecto; como el notebook está en `notebooks/`, la ruta relativa es `../data/`.

In [1]:
import pandas as pd

orders = pd.read_csv("../data/instacart_orders.csv", sep=";")
products = pd.read_csv("../data/products.csv", sep=";")
aisles = pd.read_csv("../data/aisles.csv", sep=";")
departments = pd.read_csv("../data/departments.csv", sep=";")
order_products = pd.read_csv("../data/order_products.csv", sep=";")

print("Los cinco archivos se cargaron correctamente.")

Los cinco archivos se cargaron correctamente.

### Primeros y últimos cinco registros de cada DataFrame

In [2]:
print("1. PEDIDOS (orders)")
display(orders.head())
display(orders.tail())

print("2. PRODUCTOS (products)")
display(products.head())
display(products.tail())

print("3. PASILLOS (aisles)")
display(aisles.head())
display(aisles.tail())

print("4. DEPARTAMENTOS (departments)")
display(departments.head())
display(departments.tail())

print("5. ARTÍCULOS POR PEDIDO (order_products)")
display(order_products.head())
display(order_products.tail())

1. PEDIDOS (orders)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
1,1690866,163593,5,5,12,9.0
2,1454967,39980,4,5,19,2.0
3,1768857,82516,56,0,20,10.0
4,3007858,196724,2,4,12,17.0

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
478962,3210681,5617,5,1,14,7.0
478963,3270802,112087,2,3,13,6.0
478964,885349,82944,16,2,11,6.0
478965,216274,4391,3,3,8,8.0
478966,2071924,1730,18,1,14,15.0

2. PRODUCTOS (products)

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

,product_id,product_name,aisle_id,department_id
49689,49690,HIGH PERFORMANCE ENERGY DRINK,64,7
49690,49691,ORIGINAL PANCAKE & WAFFLE MIX,130,14
49691,49692,ORGANIC INSTANT OATMEAL LIGHT MAPLE BROWN SUGAR,130,14
49692,49693,SPRING WATER BODY WASH,127,11
49693,49694,BURRITO- STEAK & CHEESE,38,1

3. PASILLOS (aisles)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

     aisle_id                       aisle
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

4. DEPARTAMENTOS (departments)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

    department_id department
16             17  household
17             18     babies
18             19     snacks
19             20       deli
20             21    missing

5. ARTÍCULOS POR PEDIDO (order_products)

   order_id  product_id  add_to_cart_order  reordered
0   2141543       11440               17.0          0
1    567889        1560                1.0          1
2   2261212       26683                1.0          1
3    491251        8670               35.0          1
4   2571142        1940                5.0          1

         order_id  product_id  add_to_cart_order  reordered
4545002    577211       15290               12.0          1
4545003   1219554       21914                9.0          0
4545004    692640       47766                4.0          1
4545005    319435         691                8.0          1
4545006   1398151       28733                9.0          0

### Dimensiones de cada DataFrame (`shape`)

In [3]:
print("Pedidos (orders):", orders.shape)
print("Productos (products):", products.shape)
print("Pasillos (aisles):", aisles.shape)
print("Departamentos (departments):", departments.shape)
print("Artículos por pedido (order_products):", order_products.shape)

Pedidos (orders): (478967, 6)
Productos (products): (49694, 4)
Pasillos (aisles): (134, 2)
Departamentos (departments): (21, 2)
Artículos por pedido (order_products): (4545007, 4)

### Análisis de las dimensiones de los DataFrames

**1. ¿Cuál de los cinco DataFrames contiene más registros?**

`order_products`, con 4.545.007 filas y 4 columnas. Es el más grande porque cada pedido tiene varios artículos y cada artículo es una fila.

**2. ¿Cuál contiene menos columnas?**

`aisles` y `departments`, con 2 columnas cada uno: un identificador y un nombre. Son tablas de referencia.

**3. ¿Qué diferencias identifica entre los datos de pedidos y los datos de productos?**

- `orders` (478.967 filas, 6 columnas) registra **eventos de compra**: cada fila es un pedido de un usuario, con día, hora y tiempo desde el pedido anterior. Crece cada vez que un cliente compra.
- `products` (49.694 filas, 4 columnas) es un **catálogo**: cada fila describe un producto y su clasificación (pasillo y departamento). No cambia con cada compra.
- `orders` tiene solo columnas numéricas, mientras que `products` incluye texto (`product_name`).
- Las dos tablas no se conectan directamente: se relacionan a través de `order_products`, que contiene `order_id` y `product_id`.

**4. ¿Por qué es importante conocer las dimensiones de un conjunto de datos?**

Las dimensiones indican cuántos registros y cuántas variables hay. Con ellas se puede verificar que la carga fue completa (coincide con lo esperado: 478.967, 49.694, 134, 21 y 4.545.007 registros), estimar el costo de las operaciones (4,5 millones de filas tardan más) y comparar el total de filas con los valores no nulos para detectar datos ausentes.

# Momento 3. Reconocimiento de la estructura y calidad inicial de los datos

Se usan los atributos `columns`, `dtypes` y `shape`, y el método `info()`. No se corrigen ni se eliminan registros en esta fase.

### 3.1 Nombres de columnas y tipos de datos (`columns` y `dtypes`)

In [4]:
dataframes = {
    "orders": orders,
    "products": products,
    "aisles": aisles,
    "departments": departments,
    "order_products": order_products
}

for nombre, df in dataframes.items():
    print("\n---", nombre, "---")
    print("Dimensiones (shape):", df.shape)
    print("Columnas:", df.columns.tolist())
    print("Tipos de datos:")
    print(df.dtypes)

--- orders ---
Dimensiones (shape): (478967, 6)
Columnas: ['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']
Tipos de datos:
order_id                    int64
user_id                     int64
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

--- products ---
Dimensiones (shape): (49694, 4)
Columnas: ['product_id', 'product_name', 'aisle_id', 'department_id']
Tipos de datos:
product_id       int64
product_name       str
aisle_id         int64
department_id    int64
dtype: object

--- aisles ---
Dimensiones (shape): (134, 2)
Columnas: ['aisle_id', 'aisle']
Tipos de datos:
aisle_id    int64
aisle         str
dtype: object

--- departments ---
Dimensiones (shape): (21, 2)
Columnas: ['department_id', 'department']
Tipos de datos:
department_id    int64
department         str
dtype: object

--- order_products ---
Dimensiones (shape): (4545007, 4)
Columnas: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']
Tipos de datos:
order_id               int64
product_id             int64
add_to_cart_order    float64
reordered              int64
dtype: object

### 3.2 Resumen con `info()`

En `order_products` se usa `show_counts=True`: como la tabla tiene más de 1,7 millones de filas, Pandas oculta por defecto el conteo de valores no nulos y con este parámetro se obliga a mostrarlo.

In [5]:
for nombre, df in dataframes.items():
    print(f"\n--- Información del archivo: {nombre} ---")
    df.info(show_counts=True)

--- Información del archivo: orders ---
<class 'pandas.DataFrame'>
RangeIndex: 478967 entries, 0 to 478966
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                478967 non-null  int64
 1   user_id                 478967 non-null  int64
 2   order_number            478967 non-null  int64
 3   order_dow               478967 non-null  int64
 4   order_hour_of_day       478967 non-null  int64
 5   days_since_prior_order  450148 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 21.9 MB

--- Información del archivo: products ---
<class 'pandas.DataFrame'>
RangeIndex: 49694 entries, 0 to 49693
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49694 non-null  int64
 1   product_name   48436 non-null  str
 2   aisle_id       49694 non-null  int64
 3   department_id  49694 non-null  int64
dtypes: int64(3), str(1)
memory usage: 1.5 MB

--- Información del archivo: aisles ---
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.2 KB

--- Información del archivo: departments ---
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

--- Información del archivo: order_products ---
<class 'pandas.DataFrame'>
RangeIndex: 4545007 entries, 0 to 4545006
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           4545007 non-null  int64
 1   product_id         4545007 non-null  int64
 2   add_to_cart_order  4544171 non-null  float64
 3   reordered          4545007 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 138.7 MB

### 3.3 Comparación entre el número de registros y los valores no nulos

In [6]:
for nombre, df in dataframes.items():
    comparacion = pd.DataFrame({
        "registros": df.shape[0],
        "no_nulos": df.notnull().sum(),
        "ausentes": df.isnull().sum()
    })
    print(f"\n--- {nombre} ---")
    display(comparacion)

--- orders ---

                        registros  no_nulos  ausentes
order_id                   478967    478967         0
user_id                    478967    478967         0
order_number               478967    478967         0
order_dow                  478967    478967         0
order_hour_of_day          478967    478967         0
days_since_prior_order     478967    450148     28819

--- products ---

               registros  no_nulos  ausentes
product_id         49694     49694         0
product_name       49694     48436      1258
aisle_id           49694     49694         0
department_id      49694     49694         0

--- aisles ---

          registros  no_nulos  ausentes
aisle_id        134       134         0
aisle           134       134         0

--- departments ---

               registros  no_nulos  ausentes
department_id         21        21         0
department            21        21         0

--- order_products ---

                   registros  no_nulos  ausentes
order_id             4545007   4545007         0
product_id           4545007   4545007         0
add_to_cart_order    4545007   4544171       836
reordered            4545007   4545007         0

### 3.4 Verificaciones adicionales sobre la calidad de los datos

- ¿Los valores ausentes de `days_since_prior_order` corresponden al primer pedido de cada cliente?
- ¿Hay filas completamente repetidas en algún archivo?

In [7]:
primeros_pedidos = (orders["order_number"] == 1).sum()
ausentes_dias = orders["days_since_prior_order"].isnull().sum()
ausentes_en_primer_pedido = orders[orders["order_number"] == 1]["days_since_prior_order"].isnull().sum()

print("Pedidos con order_number == 1:", primeros_pedidos)
print("Valores ausentes en days_since_prior_order:", ausentes_dias)
print("Ausentes que están en un primer pedido:", ausentes_en_primer_pedido)

print("\nFilas duplicadas por archivo:")
for nombre, df in dataframes.items():
    print(f"{nombre}: {df.duplicated().sum()}")

Pedidos con order_number == 1: 28819
Valores ausentes en days_since_prior_order: 28819
Ausentes que están en un primer pedido: 28819

Filas duplicadas por archivo:
orders: 15
products: 0
aisles: 0
departments: 0
order_products: 0

### 3.5 Tabla de diagnóstico

In [8]:
diagnostico = pd.DataFrame({
    "archivo": [
        "instacart_orders.csv",
        "products.csv",
        "aisles.csv",
        "departments.csv",
        "order_products.csv"
    ],
    "filas": [df.shape[0] for df in dataframes.values()],
    "columnas": [df.shape[1] for df in dataframes.values()],
    "valores_ausentes": [df.isnull().sum().sum() for df in dataframes.values()],
    "observaciones": [
        "5 columnas int64 y 1 float64. days_since_prior_order tiene 28.819 ausentes, que coinciden con los primeros pedidos (order_number = 1). Hay 15 filas duplicadas.",
        "3 columnas int64 y 1 object. product_name tiene 1.258 ausentes: productos sin nombre identificable.",
        "Sin ausentes ni duplicados. El pasillo 100 se llama 'missing'.",
        "Sin ausentes ni duplicados. El departamento 21 se llama 'missing'.",
        "3 columnas int64 y 1 float64. add_to_cart_order tiene 836 ausentes; por eso es float64 aunque guarda posiciones enteras."
    ]
})

pd.set_option("display.max_colwidth", None)
display(diagnostico)

,archivo,filas,columnas,valores_ausentes,observaciones
0,instacart_orders.csv,478967,6,28819,"5 columnas int64 y 1 float64. days_since_prior_order tiene 28.819 ausentes, que coinciden con los primeros pedidos (order_number = 1). Hay 15 filas duplicadas."
1,products.csv,49694,4,1258,3 columnas int64 y 1 object. product_name tiene 1.258 ausentes: productos sin nombre identificable.
2,aisles.csv,134,2,0,Sin ausentes ni duplicados. El pasillo 100 se llama 'missing'.
3,departments.csv,21,2,0,Sin ausentes ni duplicados. El departamento 21 se llama 'missing'.
4,order_products.csv,4545007,4,836,3 columnas int64 y 1 float64. add_to_cart_order tiene 836 ausentes; por eso es float64 aunque guarda posiciones enteras.

### Diagnóstico de la estructura y calidad inicial de los datos

**Columnas de cada archivo y tipo de dato**

| Archivo | Enteros (`int64`) | Decimales (`float64`) | Texto (`object`) |
|---|---|---|---|
| `instacart_orders.csv` | order_id, user_id, order_number, order_dow, order_hour_of_day | days_since_prior_order | — |
| `products.csv` | product_id, aisle_id, department_id | — | product_name |
| `aisles.csv` | aisle_id | — | aisle |
| `departments.csv` | department_id | — | department |
| `order_products.csv` | order_id, product_id, reordered | add_to_cart_order | — |

**Campos que relacionan los conjuntos de datos**

| Campo | Relaciona | Significado |
|---|---|---|
| `order_id` | `orders` ↔ `order_products` | Qué artículos tiene cada pedido |
| `product_id` | `products` ↔ `order_products` | Qué producto es cada artículo comprado |
| `aisle_id` | `products` ↔ `aisles` | A qué pasillo pertenece cada producto |
| `department_id` | `products` ↔ `departments` | A qué departamento pertenece cada producto |

`user_id` solo aparece en `orders`; para saber qué compró un usuario hay que pasar por `order_id` hasta `order_products`.

### Respuestas a las preguntas de análisis

**¿Qué diferencias existen entre int64, float64 y object?**

- `int64`: números enteros, como identificadores, horas o posiciones.
- `float64`: números con decimales. También aparece en columnas que en realidad son enteras pero tienen valores ausentes, porque el valor ausente (`NaN`) es un decimal especial. Por eso `days_since_prior_order` y `add_to_cart_order` son `float64`.
- `object`: texto, como los nombres de productos, pasillos y departamentos.

**¿Qué información proporciona `info()` que no se obtiene directamente con `shape`?**

`shape` solo dice cuántas filas y columnas hay. `info()` agrega el nombre de cada columna, su tipo de dato, cuántos valores no nulos tiene y el uso de memoria. Gracias a `info()` se detectan los valores ausentes; con `shape` no.

**¿En qué columnas se observan valores ausentes?**

- `orders.days_since_prior_order`: 28.819 ausentes (450.148 no nulos de 478.967). Coinciden exactamente con los 28.819 pedidos con `order_number = 1`: un primer pedido no tiene pedido anterior.
- `products.product_name`: 1.258 ausentes (48.436 no nulos de 49.694).
- `order_products.add_to_cart_order`: 836 ausentes (4.544.171 no nulos de 4.545.007).
- `aisles` y `departments` no tienen ausentes.

Además, `orders` tiene 15 filas duplicadas y tanto `aisles` como `departments` incluyen una categoría llamada `missing`.

**¿Qué dificultades podrían generar estos valores en un análisis posterior?**

- Los promedios y estadísticas ignoran los `NaN`, así que se calculan sobre menos registros de los que hay.
- Si se interpretan los ausentes de `days_since_prior_order` como 0 días, se distorsiona el intervalo entre pedidos.
- Los productos sin nombre no se pueden identificar en reportes.
- Las filas duplicadas en `orders` inflan los conteos de pedidos.
- Las comparaciones con `NaN` siempre dan `False`, así que esos registros quedan fuera de los filtros sin avisar.

# Momento 4. Indexación y filtrado lógico de la información

Cada ejercicio guarda el resultado en una variable, muestra cuántos registros cumplen la condición y presenta las primeras filas.

### Ejercicio 1. Seleccionar únicamente `product_id` y `product_name` (`products`)

In [9]:
ej1 = products[["product_id", "product_name"]]

print("Registros:", ej1.shape[0], "| Columnas:", ej1.shape[1])
display(ej1.head())

Registros: 49694 | Columnas: 2

,product_id,product_name
0,1,Chocolate Sandwich Cookies
1,2,All-Seasons Salt
2,3,Robust Golden Unsweetened Oolong Tea
3,4,Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce
4,5,Green Chile Anytime Sauce

**Explicación:** se seleccionan columnas con la notación abreviada y doble corchete. No se filtra ninguna fila: se conservan los 49.694 productos, pero solo 2 de las 4 columnas. Es una forma de quedarse con la información que interesa (el identificador y el nombre).

### Ejercicio 2. Productos cuyo `department_id` es igual a 1 (`products`)

In [10]:
ej2 = products.loc[products["department_id"] == 1]

print("Productos del departamento 1:", ej2.shape[0])
display(ej2.head())

# nombre del departamento 1 en la tabla departments
display(departments.loc[departments["department_id"] == 1])

Productos del departamento 1: 4008

,product_id,product_name,aisle_id,department_id
3,4,Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce,38,1
7,8,Cut Russet Potatoes Steam N' Mash,116,1
11,12,Chocolate Fudge Layer Cake,119,1
17,18,Pizza for One Suprema Frozen Pizza,79,1
29,30,Three Cheese Ziti- Marinara with Meatballs,38,1

   department_id department
0              1     frozen

**Explicación:** el filtro lógico deja solo las filas donde `department_id == 1`. Resultan **4.008 productos**, el 8,07 % del catálogo. Al consultar `departments` se confirma que el departamento 1 es **frozen** (congelados).

### Ejercicio 3. Pedidos realizados a las 10 horas (`orders`)

In [11]:
ej3 = orders[orders["order_hour_of_day"] == 10]

print("Pedidos a las 10 horas:", ej3.shape[0])
display(ej3.head())

Pedidos a las 10 horas: 40578

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
19,294269,107523,29,2,10,1.0
28,133707,182261,1,3,10,NaN
36,3378084,127629,21,1,10,20.0
49,2161799,87345,7,0,10,24.0
51,1739741,118405,48,2,10,3.0

**Explicación:** hay **40.578 registros de pedidos** hechos a las 10:00 a. m., el 8,47 % del total. Como se verá en el Momento 6, es la hora con más pedidos.

### Ejercicio 4. Pedidos cuyo `order_dow` es igual a 0 (`orders`)

In [12]:
ej4 = orders[orders["order_dow"] == 0]

print("Pedidos con order_dow = 0:", ej4.shape[0])
display(ej4.head())

Pedidos con order_dow = 0: 84090

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
3,1768857,82516,56,0,20,10.0
5,1843871,20084,5,0,11,15.0
7,2521283,97711,2,0,18,22.0
23,3406282,19356,21,0,0,14.0
25,1895419,169793,2,0,11,8.0

**Explicación:** según el diccionario de datos, `order_dow = 0` es **domingo**. Hay **84.090 pedidos** ese día, el 17,56 % del total; es el día con más pedidos.

### Ejercicio 5. Pedidos con `order_number` superior a 10 (`orders`)

In [13]:
ej5 = orders[orders["order_number"] > 10]

print("Pedidos con order_number > 10:", ej5.shape[0])
display(ej5.head())

Pedidos con order_number > 10: 244072

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
3,1768857,82516,56,0,20,10.0
6,2511640,148233,40,3,8,2.0
8,2266494,34954,40,5,15,4.0
10,1162566,43738,33,4,11,2.0

**Explicación:** **244.072 registros** (50,96 %) corresponden al pedido número 11 o posterior de un cliente. Es decir, más de la mitad de los pedidos vienen de clientes que ya habían comprado más de 10 veces: hay una base fuerte de clientes recurrentes.

### Ejercicio 6. Pedidos con `days_since_prior_order` superior a 15 (`orders`)

In [14]:
ej6 = orders[orders["days_since_prior_order"] > 15]

print("Pedidos con más de 15 días desde el anterior:", ej6.shape[0])
display(ej6.head())

Pedidos con más de 15 días desde el anterior: 110706

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
4,3007858,196724,2,4,12,17.0
7,2521283,97711,2,0,18,22.0
14,2843219,74699,4,6,11,30.0
26,1844247,122558,4,6,18,30.0

**Explicación:** **110.706 pedidos** se hicieron más de 15 días después del pedido anterior: el 24,59 % de los 450.148 pedidos que tienen ese dato. Los 28.819 primeros pedidos (con `NaN`) quedan fuera del filtro automáticamente, porque una comparación con `NaN` siempre es `False`.

### Ejercicio 7. Registros cuyo `reordered` es igual a 1 (`order_products`)

In [15]:
ej7 = order_products[order_products["reordered"] == 1]

print("Registros de artículos recomprados:", ej7.shape[0])
display(ej7.head())

Registros de artículos recomprados: 2683838

   order_id  product_id  add_to_cart_order  reordered
1    567889        1560                1.0          1
2   2261212       26683                1.0          1
3    491251        8670               35.0          1
4   2571142        1940                5.0          1
5   2456893       21616                4.0          1

**Explicación:** **2.683.838 registros de artículos** son recompras: el cliente ya había pedido ese producto antes. Representan el 59,05 % de los 4.545.007 artículos. Son registros de artículos, no pedidos ni clientes.

### Ejercicio 8. Productos agregados en la primera posición del carrito (`order_products`)

In [16]:
ej8 = order_products[order_products["add_to_cart_order"] == 1]

print("Artículos en la primera posición del carrito:", ej8.shape[0])
print("Pedidos distintos en order_products:", order_products["order_id"].nunique())
display(ej8.head())

Artículos en la primera posición del carrito: 450046
Pedidos distintos en order_products: 450046

    order_id  product_id  add_to_cart_order  reordered
1     567889        1560                1.0          1
2    2261212       26683                1.0          1
14   1961225       37553                1.0          1
16    639939       10017                1.0          1
23    750040        8518                1.0          0

**Explicación:** **450.046 registros** tienen `add_to_cart_order = 1`. El número coincide con la cantidad de pedidos distintos en `order_products` (450.046): cada pedido tiene exactamente un primer artículo. Los 836 registros con posición ausente no entran en el filtro.

### Filtros con condiciones simultáneas

**Filtro A. Pedidos realizados a las 10 horas y con `order_number` superior a 10 (`orders`)**

In [17]:
filtro_a = orders.loc[
    (orders["order_hour_of_day"] == 10) &
    (orders["order_number"] > 10)
]

print("Pedidos a las 10 h:", ej3.shape[0])
print("Pedidos con order_number > 10:", ej5.shape[0])
print("Pedidos que cumplen ambas condiciones:", filtro_a.shape[0])
display(filtro_a.head())

Pedidos a las 10 h: 40578
Pedidos con order_number > 10: 244072
Pedidos que cumplen ambas condiciones: 21537

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
19,294269,107523,29,2,10,1.0
36,3378084,127629,21,1,10,20.0
51,1739741,118405,48,2,10,3.0
92,60724,110808,78,0,10,2.0
140,3156095,113920,14,2,10,2.0

**Explicación:** con el operador `&` deben cumplirse las dos condiciones a la vez. Quedan **21.537 pedidos**: menos que los 40.578 de las 10 h y menos que los 244.072 con más de 10 pedidos. Equivalen al 53,08 % de los pedidos de las 10 h, una proporción similar al 50,96 % de clientes recurrentes en todo el archivo.

**Filtro B. Productos del departamento 1 con `aisle_id` superior a 50 (`products`)**

In [18]:
filtro_b = products.loc[
    (products["department_id"] == 1) &
    (products["aisle_id"] > 50),
    ["product_id", "product_name", "aisle_id", "department_id"]
]

print("Productos del departamento 1:", ej2.shape[0])
print("Productos del departamento 1 con aisle_id > 50:", filtro_b.shape[0])
display(filtro_b.head())

# pasillos que aparecen en el resultado
print("\nProductos por pasillo:")
print(filtro_b["aisle_id"].value_counts())
display(aisles[aisles["aisle_id"].isin(filtro_b["aisle_id"].unique())])

Productos del departamento 1: 4008
Productos del departamento 1 con aisle_id > 50: 1618

     product_id                         product_name  aisle_id  department_id
7             8    Cut Russet Potatoes Steam N' Mash       116              1
11           12           Chocolate Fudge Layer Cake       119              1
17           18  Pizza for One Suprema  Frozen Pizza        79              1
45           46       Raisin Cinnamon Bagels 5 count        58              1
127         128             Organic Wild Blueberries       116              1

Productos por pasillo:
aisle_id
129    386
116    361
79     335
52     296
119    112
58      81
113     47
Name: count, dtype: int64

     aisle_id                    aisle
51         52         frozen breakfast
57         58     frozen breads doughs
78         79             frozen pizza
112       113             frozen juice
115       116           frozen produce
118       119           frozen dessert
128       129  frozen appetizers sides

**Explicación:** `loc[]` permite filtrar filas y elegir columnas en una sola instrucción. Quedan **1.618 de los 4.008 productos** congelados (40,37 %). Están en 7 pasillos, todos de congelados: frozen appetizers sides (129), frozen produce (116), frozen pizza (79), frozen breakfast (52), frozen dessert (119), frozen breads doughs (58) y frozen juice (113). Los pasillos con más productos congelados, ice cream ice (37) y frozen meals (38), quedan fuera porque su `aisle_id` es menor que 50.

### Respuestas a las preguntas de análisis

**¿Qué diferencia existe entre seleccionar columnas y filtrar filas?**

Seleccionar columnas reduce el número de **variables** y conserva todas las filas (ejercicio 1: 49.694 filas, 2 columnas). Filtrar filas reduce el número de **registros** según una condición y conserva todas las columnas (ejercicio 2: 4.008 filas, 4 columnas). Con `loc[]` se pueden hacer las dos cosas al tiempo (filtro B).

**¿Qué ventajas ofrece `loc[]` al consultar información específica?**

- Permite indicar en una sola instrucción qué filas (por condición o por índice) y qué columnas se quieren: `df.loc[filas, columnas]`.
- Hace el código explícito y fácil de leer.
- Permite seleccionar una celda puntual, rangos de filas y rangos de columnas, cosa que la notación abreviada no permite.

**¿Qué ocurre con la cantidad de registros cuando se aplican varias condiciones?**

Con `&` el resultado nunca puede ser mayor que el de la condición más restrictiva, porque cada registro debe cumplirlas todas. En el filtro A se pasó de 40.578 y 244.072 registros a 21.537; en el filtro B, de 4.008 a 1.618.

**¿Por qué es importante utilizar correctamente los operadores lógicos?**

Porque cambian por completo la respuesta. `&` exige que se cumplan todas las condiciones y `|` acepta que se cumpla cualquiera; confundirlos devuelve otro subconjunto de datos y lleva a conclusiones equivocadas. Además, en Pandas cada condición debe ir entre paréntesis y no se pueden usar `and` ni `or` de Python, porque generan un error. También hay que distinguir `=` (asignar) de `==` (comparar).

# Momento 5. Obtención e interpretación de indicadores básicos

### ¿Cuántos registros de pedidos contiene el archivo? (registros, pedidos y usuarios)

In [19]:
total_registros_pedidos = orders.shape[0]
total_pedidos_distintos = orders["order_id"].nunique()
total_usuarios = orders["user_id"].nunique()

print("Registros (filas) en orders:", total_registros_pedidos)
print("Valores de order_id no nulos (count):", orders["order_id"].count())
print("Pedidos distintos (order_id únicos):", total_pedidos_distintos)
print("Usuarios distintos (user_id únicos):", total_usuarios)

Registros (filas) en orders: 478967
Valores de order_id no nulos (count): 478967
Pedidos distintos (order_id únicos): 478952
Usuarios distintos (user_id únicos): 157437

### ¿Cuántos registros de productos contiene el catálogo?

In [20]:
total_productos = products.shape[0]

print("Registros de productos:", total_productos)

Registros de productos: 49694

### ¿Cuál es el promedio de `order_number`?

In [21]:
promedio_order_number = orders["order_number"].mean()

print("Promedio de order_number:", round(promedio_order_number, 2))
print("Mediana de order_number:", orders["order_number"].median())

Promedio de order_number: 17.16
Mediana de order_number: 11.0

### ¿Cuál es el promedio de `days_since_prior_order` entre los valores disponibles?

In [22]:
promedio_dias = orders["days_since_prior_order"].mean()

print("Valores disponibles:", orders["days_since_prior_order"].count())
print("Promedio de días entre pedidos:", round(promedio_dias, 2))

Valores disponibles: 450148
Promedio de días entre pedidos: 11.1

### ¿Cuántos registros de artículos tienen `reordered` igual a 1?

In [23]:
total_reordenados = order_products[order_products["reordered"] == 1]["reordered"].count()

print("Registros con reordered = 1:", total_reordenados)

Registros con reordered = 1: 2683838

### ¿Cuál es la suma de la columna `reordered`?

In [24]:
suma_reordenados = order_products["reordered"].sum()
proporcion_reordenados = order_products["reordered"].mean()

print("Suma de reordered:", suma_reordenados)
print("Proporción de recompras:", round(proporcion_reordenados * 100, 2), "%")

Suma de reordered: 2683838
Proporción de recompras: 59.05 %

### ¿Qué características estadísticas presenta `order_hour_of_day`?

In [25]:
orders["order_hour_of_day"].describe()

count    478967.000000
mean         13.446676
std           4.224986
min           0.000000
25%          10.000000
50%          13.000000
75%          16.000000
max          23.000000
Name: order_hour_of_day, dtype: float64

### ¿Qué características estadísticas presenta `add_to_cart_order`?

In [26]:
order_products["add_to_cart_order"].describe()

count    4.544171e+06
mean     8.351669e+00
std      7.080368e+00
min      1.000000e+00
25%      3.000000e+00
50%      6.000000e+00
75%      1.100000e+01
max      6.400000e+01
Name: add_to_cart_order, dtype: float64

### Tabla de indicadores

| Pregunta analizada | Valor obtenido | Interpretación |
|---|---|---|
| ¿Cuántos registros de pedidos contiene el archivo? | 478.967 registros | Son filas, no clientes. Hay 478.952 `order_id` distintos (15 filas duplicadas) y solo 157.437 usuarios distintos: en promedio, unos 3 pedidos por usuario en este archivo. |
| ¿Cuántos registros de productos contiene el catálogo? | 49.694 | Cantidad de productos del catálogo; 48.436 tienen nombre. |
| ¿Cuál es el promedio de `order_number`? | 17,16 (mediana 11) | Es el promedio del número de pedido de cada registro, no la cantidad de pedidos por cliente. La media es mayor que la mediana porque algunos clientes llegan hasta 100 pedidos y elevan el promedio. |
| ¿Cuál es el promedio de `days_since_prior_order`? | 11,10 días | Calculado con los 450.148 valores disponibles; los 28.819 ausentes son primeros pedidos. Mínimo 0, mediana 7 y máximo 30 días. |
| ¿Cuántos registros de artículos tienen `reordered` = 1? | 2.683.838 | Artículos recomprados. Es un conteo de artículos, no de pedidos ni de clientes. |
| ¿Cuál es la suma de la columna `reordered`? | 2.683.838 | Coincide con el conteo porque la columna solo vale 0 o 1. Su promedio, 0,5905, indica que el 59,05 % de los artículos son recompras. |
| ¿Qué características presenta `order_hour_of_day`? | Media 13,45; desv. 4,23; mín. 0; Q1 10; mediana 13; Q3 16; máx. 23 | La mitad central de los pedidos ocurre entre las 10:00 y las 16:00. Todos los valores están en el rango válido 0–23. |
| ¿Qué características presenta `add_to_cart_order`? | 4.544.171 valores; media 8,35; desv. 7,08; mín. 1; Q1 3; mediana 6; Q3 11; máx. 64 | La mitad de los artículos están entre las posiciones 3 y 11. La media supera a la mediana porque hay pocos carritos muy grandes (hasta 64 artículos). |

**Registros, pedidos y usuarios no son lo mismo.** El archivo `orders` tiene 478.967 filas, pero 478.952 pedidos distintos y 157.437 clientes distintos. En `order_products`, los 4.545.007 registros son artículos de 450.046 pedidos. Por eso ningún conteo de filas se interpreta como número de clientes.

**Sobre los datos ausentes:** Pandas excluye automáticamente los `NaN` al calcular `mean()`, `count()` y `describe()`, por lo que esas estadísticas se calculan solo con los valores disponibles.

# Momento 6. Resolución del problema y presentación del producto

### Consultas de apoyo para responder las preguntas iniciales

**Pregunta 1. Distribución de los pedidos por hora**

In [27]:
pedidos_por_hora = orders["order_hour_of_day"].value_counts().sort_index()
print(pedidos_por_hora)

pedidos_9_a_16 = orders[(orders["order_hour_of_day"] >= 9) & (orders["order_hour_of_day"] <= 16)].shape[0]
print("\nPedidos entre las 9 y las 16 h:", pedidos_9_a_16)
print("Porcentaje:", round(pedidos_9_a_16 / orders.shape[0] * 100, 2), "%")

order_hour_of_day
0      3180
1      1763
2      1004
3       770
4       765
5      1371
6      4215
7     13043
8     25024
9     35896
10    40578
11    40032
12    38034
13    39007
14    39631
15    39789
16    38112
17    31930
18    25510
19    19547
20    14624
21    11019
22     8512
23     5611
Name: count, dtype: int64

Pedidos entre las 9 y las 16 h: 311079
Porcentaje: 64.95 %

**Pregunta 2. Productos del departamento 1**

In [28]:
productos_dep1 = products[products["department_id"] == 1]

print("Productos del departamento 1:", productos_dep1.shape[0])
print("Porcentaje del catálogo:", round(productos_dep1.shape[0] / products.shape[0] * 100, 2), "%")
print("\nPasillos con más productos del departamento 1:")
print(productos_dep1["aisle_id"].value_counts().head(5))
display(aisles[aisles["aisle_id"].isin([37, 38])])

Productos del departamento 1: 4008
Porcentaje del catálogo: 8.07 %

Pasillos con más productos del departamento 1:
aisle_id
37     1091
38      881
129     386
116     361
79      335
Name: count, dtype: int64

    aisle_id          aisle
36        37  ice cream ice
37        38   frozen meals

**Pregunta 3. Proporción de artículos recomprados**

In [29]:
proporcion = order_products[order_products["reordered"] == 1].shape[0] / order_products.shape[0]

print("Proporción de recompras:", round(proporcion * 100, 2), "%")

Proporción de recompras: 59.05 %

**Consultas complementarias: pedidos por día de la semana y departamentos con más productos**

In [30]:
print("Pedidos por día de la semana (0 = domingo):")
print(orders["order_dow"].value_counts().sort_index())

print("\nDepartamentos con más productos en el catálogo:")
top_departamentos = products["department_id"].value_counts().head(5)
print(top_departamentos)
display(departments[departments["department_id"].isin(top_departamentos.index)])

Pedidos por día de la semana (0 = domingo):
order_dow
0    84090
1    82185
2    65833
3    60912
4    59810
5    63488
6    62649
Name: count, dtype: int64

Departamentos con más productos en el catálogo:
department_id
11    6564
19    6264
13    5372
7     4366
1     4008
Name: count, dtype: int64

    department_id     department
0               1         frozen
6               7      beverages
10             11  personal care
12             13         pantry
18             19         snacks

## Síntesis: respuesta a la pregunta orientadora

Con Pandas fue posible cargar los cinco archivos, reconocer su estructura y calidad, consultar subconjuntos específicos con indexación y filtros, y calcular indicadores básicos. Esto permitió describir cuándo compran los clientes, qué tan seguido vuelven a comprar y qué tan frecuente es la recompra de productos.

### 1. Preguntas de análisis formuladas y sus respuestas

**¿A qué horas del día se registran los pedidos y cuál es la distribución de los pedidos por hora?**

Los pedidos se registran en las 24 horas, pero con una distribución muy desigual. Entre las 0 y las 5 h hay muy pocos (el mínimo es a las 4 h, con 765). Desde las 7 h suben rápidamente, alcanzan el máximo a las **10 h con 40.578 pedidos** y se mantienen por encima de 35.000 por hora hasta las 16 h. Entre las 9 y las 16 h se concentran 311.079 pedidos, el **64,95 %** del total. Desde las 17 h la cantidad baja de forma constante hasta 5.611 a las 23 h.

**¿Qué productos pertenecen al departamento 1 y cuántos registros cumplen esta condición?**

El departamento 1 es **frozen (congelados)** y tiene **4.008 productos**, el 8,07 % del catálogo. Los pasillos con más productos de este departamento son ice cream ice (1.091) y frozen meals (881).

**¿Qué proporción de los registros de artículos corresponde a productos que ya habían sido comprados anteriormente?**

**2.683.838 de 4.545.007 registros**, es decir, el **59,05 %**. Más de la mitad de lo que se agrega a los carritos son productos que el cliente ya había comprado.

### 2. Principales hallazgos sobre pedidos y productos

- El archivo de pedidos tiene 478.967 registros, 478.952 pedidos distintos y 157.437 clientes distintos.
- El domingo (84.090) es el día con más pedidos, seguido por el día 1 (82.185). El día con menos pedidos es el 4 (59.810).
- La mitad de los pedidos ocurre entre las 10 y las 16 h.
- El 50,96 % de los pedidos corresponde al pedido número 11 o posterior de un cliente.
- En promedio pasan 11,10 días entre pedidos (mediana 7). El 24,59 % de los pedidos con este dato se hizo más de 15 días después del anterior.
- La posición promedio de un artículo en el carrito es 8,35 y la mediana es 6: la mitad de los artículos se agregan entre las posiciones 3 y 11.
- Los departamentos con más productos en el catálogo son personal care (6.564), snacks (6.264) y pantry (5.372).

### 3. Cómo la indexación y los filtros permitieron consultar información relevante

- La **selección de columnas** (`products[["product_id", "product_name"]]`) permitió quedarse solo con las variables útiles para una consulta.
- El **filtrado lógico** (`orders[orders["order_hour_of_day"] == 10]`) aisló los registros que cumplen una condición, y con `shape[0]` se obtuvo cuántos son.
- **`loc[]`** permitió filtrar filas y elegir columnas en una sola instrucción, y buscar el nombre de un departamento o pasillo a partir de su identificador.
- Las **condiciones simultáneas con `&`** respondieron preguntas más precisas, como cuántos pedidos de clientes recurrentes se hacen a las 10 h (21.537).
- Combinar filtros con `count()`, `sum()` y `mean()` convirtió los subconjuntos en indicadores, como el porcentaje de recompra.

### 4. Limitaciones identificadas en los conjuntos de datos

- **Valores ausentes:** 28.819 en `days_since_prior_order` (primeros pedidos), 1.258 en `product_name` y 836 en `add_to_cart_order`. Las estadísticas de esas columnas usan solo los valores disponibles.
- **Duplicados:** `orders` tiene 15 filas repetidas, por lo que el número de filas no es igual al de pedidos distintos.
- **Categorías sin clasificar:** `aisles` y `departments` incluyen la categoría `missing`.
- **Cobertura parcial:** `order_products` tiene artículos de 450.046 pedidos, menos que los 478.952 de `orders`; no todos los pedidos tienen su detalle de productos.
- **Datos reducidos y modificados:** el conjunto es una versión reducida del original publicado por Instacart, con ausentes y duplicados introducidos a propósito.
- **Variables codificadas:** días, pasillos y departamentos son números; su significado depende del diccionario y de las tablas de referencia. Solo se sabe con certeza que `order_dow = 0` es domingo.
- **Información no disponible:** no hay precios, fechas exactas ni datos de los clientes, así que no se pueden analizar ventas ni causas de los patrones.

### 5. Conclusiones sustentadas en los resultados

1. **La actividad de compra se concentra en horario diurno y el domingo es el día de mayor demanda.** El 64,95 % de los pedidos ocurre entre las 9 y las 16 h, con máximo a las 10 h (40.578), y el domingo es el día con más pedidos (84.090). Instacart puede reforzar su capacidad de entrega en esas franjas.
2. **Los clientes son mayoritariamente recurrentes y fieles a sus productos.** El 50,96 % de los pedidos es el pedido 11 o posterior del cliente, y el 59,05 % de los artículos son recompras. Recomendar productos ya comprados es una estrategia con mucho potencial.
3. **Explorar la calidad de los datos fue indispensable para interpretar bien los resultados.** Sin `info()` y sin comparar filas con valores únicos se habría confundido 478.967 registros con clientes, cuando son 157.437 usuarios; y el promedio de 11,10 días entre pedidos solo es válido aclarando que excluye los 28.819 primeros pedidos.